# Generated by Django 2.0.1 on 2018-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibl', '0002_auto_20180114_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='deathday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
